FROM quay.io/centos/centos:stream10
LABEL maintainer="jasper.berton@team.blue" purpose="ovirt_provider_ovn_integ_tests"

# The copr plugin is installed by default on el8stream
RUN dnf -y install yum-plugin-copr \
    && \
    dnf copr enable -y ovirt/ovirt-master-snapshot centos-stream-10-x86_64 \
    && \
    dnf install -y ovirt-release-master \
    && \
    dnf update -y \
    && \
    # Without it the ovirt-openvswitch fails to install
    # It seems that the el8s container has systemd installed by default
    dnf install -y systemd \
    && \
    dnf install -y \
        git \
        kernel \
        make \
        python3-devel  \
        rpm-build \
        # Install ovirt-provider-ovn for its dependencies
        ovirt-provider-ovn \
    && \
    dnf remove -y --noautoremove ovirt-provider-ovn \
    && \
    dnf clean all \
    && \
    mkdir -p /etc/ovirt-provider-ovn/conf.d/

COPY automation/containers/ovirt-provider-ovn/10-integrationtest.conf /etc/ovirt-provider-ovn/conf.d/

COPY automation/containers/ovirt-provider-ovn/ovn-northd.conf /etc/sysconfig/ovn-northd

COPY automation/containers/ovirt-provider-ovn/boot-northd.sh /boot-northd.sh

VOLUME ["/ovirt-provider-ovn-rpms"]

CMD ["/usr/sbin/init"]