FROM quay.io/centos/centos:stream9
LABEL maintainer="amusil@redhat.com" purpose="ovirt_provider_ovn_integ_tests"

# The copr plugin is installed by default on el8stream
RUN dnf -y install yum-plugin-copr \
    && \
    dnf copr enable -y ovirt/ovirt-master-snapshot centos-stream-9-x86_64 \
    && \
    dnf install -y ovirt-release-master \
    && \
    dnf update -y \
    && \
    # Without it the ovirt-openvswitch fails to install
    # It seems that the el8s container has systemd installed by default
    dnf install -y systemd \
    && \
    dnf install -y \
        python3-pip \
        dhclient \
        iputils \
        NetworkManager-config-server \
        ovirt-openvswitch \
        ovirt-openvswitch-ovn-common \
        ovirt-openvswitch-ovn-host \
        ovirt-python-openvswitch \
    && \
    dnf clean all

RUN python3 -m pip install mock netaddr==0.7.19 ovsdbapp requests_mock pytest


COPY automation/containers/ovn-controller/ovn-controller.conf /etc/sysconfig/ovn-controller

COPY automation/containers/ovn-controller/boot-controller.sh /boot-controller.sh

CMD ["/usr/sbin/init"]
