name: CI
on:
  push:
    branches: [master, ovirt-4.4, centos10-upgrade]
  pull_request:

env:
  EXPORT_DIR: exported-artifacts
  PYTHONPATH: ${{ github.workspace }}
jobs:
  check:
    runs-on: ubuntu-latest
    name: check and test ${{ matrix.tag }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: centos-9
            container-name: el9stream
          - tag: centos-10
            container-name: el10stream
    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install dependencies
      run: dnf install -y python3

    - name: Install python dependencies
      run: python3 -m pip install tox mock netaddr==0.7.19 ovsdbapp requests_mock pytest

    - name: Run check
      run: make check

    - name: Run unit tests
      run: make unittest

    - name: run lint
      run: make lint

    - name: run coverage
      run: make coverage

  integration-tests:
    env:
      RUN_INTEG_TESTS: 1
      IMAGE_TAG: ${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [ el9stream, el10stream ]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt remove -y python3-packaging
          sudo apt install podman python3-pip
      - name: Run integration tests
        run: sudo -E ./automation/create_it_env.sh
      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: ovirt-provider-ovn-integ-tests-${{ matrix.tag }}
          path: ${{ env.EXPORT_DIR }}
          retention-days: 5

  rpm:
    runs-on: ubuntu-latest
    name: rpm-${{ matrix.tag }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: centos-9
            container-name: el9stream
          - tag: centos-10
            container-name: el10stream

    container: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}
    steps:
    - uses: actions/checkout@v4
    - name: Build RPMs
      run: ./automation/rpm.sh
    - uses: ovirt/upload-rpms-action@main
      with:
        directory: ${{ env.EXPORT_DIR }}
